---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: elasticsearch-service
    labels:
      name: elasticsearch
  spec:
    selector:
      name: elasticsearch 
    type: NodePort
    ports:
    - name: http
      port: 9200
      protocol: TCP
      nodePort: 30200
    - name: transport
      port: 9300
      protocol: TCP
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    name: elasticsearch
    labels:
      name: elasticsearch
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: elasticsearch
      spec:
        containers:
          - name: elasticsearch
            image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
            ports:
            - containerPort: 9200
              name: http
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
            volumeMounts:
            - mountPath: /data
              name: storage
        volumes:
        - name: storage
#           Use emptydir on free clusters         
          emptyDir: {}
#          persistentVolumeClaim:
#            claimName: tdwistorage
kind: "List"
