---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: sherlock-service
    labels:
      name: sherlock-service
      context: sherlock-context
  spec:
    type: NodePort
    ports:
      # the port that this service should serve on
      - port: 80
        nodePort: 32123
    # label keys and values that must match in order to receive traffic for this service
    selector:
      name: sherlock-agent
      context: sherlock-context
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: sherlock-agent
    labels:
      name: sherlock-agent
      context: sherlock-context
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: sherlock-agent
          context: sherlock-context
      spec:
        containers:
        - name: sherlock
          image: de.icr.io/bluereplyde/sherlock:latest
          volumeMounts:
            - mountPath: /data
              name: file-store
          ports:
          - containerPort: 80
        volumes:
          - name: file-store
            # use an emptydir for now.
            emptyDir: {}

kind: "List"
