---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: kibana-service
    labels:
      name: kibana
  spec:
    selector:
      name: kibana 
    type: NodePort
    ports:
     - port: 80
       protocol: TCP
       targetPort: 5601
       nodePort: 30101
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    name: kibana
    labels:
      name: kibana
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: kibana
      spec:
        containers:
          - name: kibana
            image: docker.elastic.co/kibana/kibana-oss:6.2.2
            env:
            - name: "ELASTICSEARCH_URL"
              value: "https://admin:RYZUAYORFMEGJRCT@portal-ssl223-11.bmix-lon-yp-2012af18-4749-4d32-94a6-09573ff5ee35.3259324498.composedb.com:26611"
            - name: "ELASTICSEARCH_USERNAME"
              value: "admin"              
            - name: "ELASTICSEARCH_PASSWORD"
              value: "RYZUAYORFMEGJRCT"            
            ports:
              - containerPort: 5601
                name: http
                protocol: TCP
kind: "List"
