---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: kibana-service
    labels:
      name: kibana
  spec:
    selector:
      name: kibana 
    type: NodePort
    ports:
     - port: 80
       protocol: TCP
       targetPort: 5601
       nodePort: 30101
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    name: kibana
    labels:
      name: kibana
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: kibana
      spec:
        containers:
          - name: kibana
            image: kibana
            env:
            - name: "ELASTICSEARCH_URL"
              value: "http://elasticsearch-service:9200"
            ports:
              - containerPort: 5601
                name: http
                protocol: TCP
kind: "List"
