---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: nutch-service
    labels:
      name: nutch-service
      context: nutch-context
  spec:
    type: NodePort
    ports:
      # the port that this service should serve on
      - port: 8081
        nodePort: 30081
    # label keys and values that must match in order to receive traffic for this service
    selector:
      name: nutch-agent
      context: nutch-context
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: nutch-agent
    labels:
      name: nutch-agent
      context: nutch-context
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: nutch-agent
          context: nutch-context
      spec:
        containers:
        - name: nutch
          image: pure/nutch-mongo:alpine
          command: ["/nutch/bin/nutch"]
          args: ["nutchserver"]
          ports:
          - containerPort: 8081
- apiVersion: v1
  kind: Service
  metadata:
    name: mongo
    labels:
      name: mongo-service
      context: nutch-context
  spec:
    type: NodePort
    ports:
      - port: 27017
        nodePort: 30017 
    selector:
      name: mongo
      context: nutch-context
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: mongodb
    labels:
      name: mongo
      context: nutch-context
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: mongo
          context: nutch-context
      spec:
        hostname: mongo
        containers:
        - name: mongo
          image: mongo:3.2
kind: "List"

