---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    name: transporter
    labels:
      name: transporter
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: transporter
      spec:
        containers:
          - name: transporter
            image: quay.io/compose/transporter:latest
kind: "List"
